// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMEbiyi7ofhnEiFQ_boLITMy9TSPREwr4',
    appId: '1:10763486161:web:3ccd8ffa9a6c3953f056f0',
    messagingSenderId: '10763486161',
    projectId: 'listed-app-delhi',
    authDomain: 'listed-app-delhi.firebaseapp.com',
    storageBucket: 'listed-app-delhi.firebasestorage.app',
    measurementId: 'G-B4ZFXBYQHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIM9e2TE-bZZKUwkrEoeObZl_LCIdGYs',
    appId: '1:10763486161:android:4303c32b51e84b67f056f0',
    messagingSenderId: '10763486161',
    projectId: 'listed-app-delhi',
    storageBucket: 'listed-app-delhi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyvd_GLNBGCfta-NZec1dW50p9HPnK7y0',
    appId: '1:10763486161:ios:76b5cec873a7aa53f056f0',
    messagingSenderId: '10763486161',
    projectId: 'listed-app-delhi',
    storageBucket: 'listed-app-delhi.firebasestorage.app',
    iosBundleId: 'com.example.listedd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyvd_GLNBGCfta-NZec1dW50p9HPnK7y0',
    appId: '1:10763486161:ios:5ccc7122022c27c6f056f0',
    messagingSenderId: '10763486161',
    projectId: 'listed-app-delhi',
    storageBucket: 'listed-app-delhi.firebasestorage.app',
    iosBundleId: 'com.example.listed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMEbiyi7ofhnEiFQ_boLITMy9TSPREwr4',
    appId: '1:10763486161:web:da31d97d1ce6b088f056f0',
    messagingSenderId: '10763486161',
    projectId: 'listed-app-delhi',
    authDomain: 'listed-app-delhi.firebaseapp.com',
    storageBucket: 'listed-app-delhi.firebasestorage.app',
    measurementId: 'G-XC38TDML65',
  );
}
